export const blogsData=[
    {
        id:1,
        title:"html",
      body:"Dolores ut dolor dolore et stet sea et. Voluptua no sit erat eirmod est et consetetur gubergren. Est erat ipsum et tempor lorem. Erat sanctus est sed sanctus ipsum rebum vero eirmod. No sed dolores no ipsum kasd et gubergren aliquyam et. Et diam ea invidunt rebum clita consetetur vero. Voluptua lorem et consetetur duo. Est vero ipsum justo sadipscing sit dolores eos erat. Aliquyam consetetur kasd sed dolore erat rebum stet. Eos amet est ipsum invidunt rebum diam takimata. Et dolor diam rebum erat eirmod amet vero, elitr justo stet vero sadipscing elitr ea eirmod dolor et, elitr dolore takimata lorem vero duo at consetetur diam. Diam magna dolores ipsum sed sea kasd clita. Vero ea sit dolor elitr invidunt, dolor ut ipsum lorem et diam et dolor, dolor stet diam sed sea. Kasd nonumy amet et consetetur stet aliquyam, dolore gubergren et ipsum sit et est. Tempor diam aliquyam invidunt labore sanctus. Eos vero gubergren nonumy ea dolor duo aliquyam voluptua. Et eos rebum erat amet amet ipsum labore consetetur. Dolore kasd accusam aliquyam dolore, rebum ut eos amet at stet. Dolor lorem amet erat elitr sed diam justo. Takimata et dolore justo voluptua diam sed. Diam elitr."
    },
    {
        id:2,
        title:"Nodejs",
      body:"Kasd sea aliquyam diam eos no vero ipsum, diam tempor clita nonumy et sanctus sadipscing est ipsum sanctus. Et dolor diam vero sanctus at accusam amet magna rebum. Diam sanctus justo erat ut est stet dolores elitr, sea accusam sadipscing aliquyam diam, labore sit elitr labore ea invidunt lorem lorem sed. Ipsum sadipscing ipsum voluptua at ea, nonumy sed sanctus gubergren sit sit rebum nonumy, ea duo et lorem sit amet eirmod, elitr sanctus et diam sadipscing sed aliquyam et at at, ut sadipscing sit labore lorem diam gubergren ut et, dolor sanctus sit sed invidunt lorem sed sadipscing sed. Aliquyam sit ipsum erat erat eos erat sea amet. Sea erat eirmod amet et consetetur consetetur et elitr sed, stet at consetetur voluptua at, nonumy eos sadipscing sanctus et, diam gubergren at justo ea, eos tempor ipsum dolore no diam dolor diam. Et ipsum sanctus diam stet justo eos. Nonumy ipsum ipsum diam et sea voluptua, vero rebum dolor rebum ipsum. Dolor labore ipsum erat labore ut sadipscing sit sed ut. Sanctus sed at no diam sea invidunt. Ut at no labore voluptua et lorem lorem, justo vero sanctus et erat. Dolore ea elitr clita aliquyam et dolores clita, no."
    },
    {
        id:3,
        title:"javaScript",
      body:"No sanctus consetetur diam duo no at ipsum, duo dolore aliquyam diam ea sadipscing. Vero stet diam voluptua sit rebum lorem gubergren, takimata nonumy et amet et, takimata sit ea rebum lorem tempor no, aliquyam duo ipsum gubergren tempor amet diam at et. Eos clita et stet dolor aliquyam nonumy sit invidunt et, amet vero voluptua takimata diam nonumy et accusam nonumy diam. Labore lorem labore invidunt sadipscing lorem est erat vero, et tempor et dolores labore aliquyam lorem no. Ipsum nonumy ipsum clita magna diam lorem ea accusam sit, at takimata ipsum et sit magna et dolore. Sanctus est labore ea kasd elitr. Eos gubergren elitr invidunt eirmod sit sadipscing duo sea magna, eos dolores lorem elitr sit. Ipsum kasd clita ea sadipscing et erat eirmod duo et. No voluptua stet no ut sed. Sit diam sed labore takimata. Nonumy rebum aliquyam voluptua magna diam, justo dolor et voluptua dolores ea aliquyam takimata, invidunt clita voluptua sed ut dolore amet sea elitr duo, est dolor accusam nonumy elitr est consetetur dolores dolor, voluptua sit sit tempor labore amet amet stet voluptua. Nonumy sadipscing sit ea labore dolores, lorem duo ipsum takimata lorem stet invidunt dolore gubergren sed. Et dolores."
    },
    {
        id:4,
        title:"react",
      body:"Tempor sit eos no sit ea lorem at sadipscing. Takimata lorem sit magna lorem est accusam takimata erat et, dolor voluptua est et et diam at accusam et aliquyam. Rebum magna vero accusam gubergren, consetetur accusam justo eos lorem diam dolor at dolore, consetetur ea et accusam est. Et erat nonumy erat sadipscing diam, kasd labore dolores sanctus diam invidunt labore ipsum eirmod diam, sit diam ea sit accusam et dolores eos tempor. Nonumy dolore vero erat clita sea ipsum, ea clita dolor ipsum ipsum, no rebum ipsum ipsum ut duo sed aliquyam ut et, est amet sadipscing ea erat ea sanctus rebum. Takimata et elitr at et rebum vero elitr ipsum labore, clita lorem sit invidunt at. Stet magna accusam rebum tempor no et duo. Ipsum sadipscing ipsum ipsum sit sit dolores invidunt nonumy at, est nonumy ipsum sanctus ipsum amet vero, et no no duo consetetur diam labore stet et, amet justo lorem sadipscing lorem vero diam tempor ea lorem. Amet diam accusam sit tempor et tempor rebum sit. Kasd ea dolor nonumy invidunt gubergren ipsum erat. Tempor magna consetetur accusam clita diam dolor magna et, et eirmod sed rebum magna amet rebum no, at erat ut duo.Elitr dolor dolore lorem stet kasd sit stet stet sed, et sea ea et vero voluptua sed aliquyam at tempor"
    },
    {
        id:5,
        title:"java",
      body:"Elitr dolor At vero erat magna et dolor dolores rebum labore elitr rebum, invidunt stet ipsum amet sit, no est sanctus voluptua sanctus est amet stet ipsum, sed magna elitr voluptua dolores diam sit aliquyam diam, est duo tempor nonumy est, ea elitr sanctus est no ut sed, dolore ipsum sed rebum clita dolores accusam et sit. At amet est rebum nonumy. Dolore takimata et sed lorem amet, ut labore rebum sea diam. Gubergren lorem nonumy et consetetur takimata kasd no, et clita labore rebum sadipscing aliquyam, vero amet sea duo ut sed dolor eos elitr, gubergren erat at amet sadipscing sit no dolores. Est est magna duo diam sed elitr sit. Vero diam dolor diam kasd ipsum stet diam et vero, amet voluptua diam vero at, elitr aliquyam takimata amet accusam sed clita tempor diam aliquyam, invidunt sit eos tempor rebum eirmod clita. Sit clita aliquyam stet et. Gubergren labore erat stet accusam duo sed. Stet diam nonumy dolor et. Justo invidunt dolor dolores gubergren gubergren erat sit invidunt, dolores sed labore magna dolor voluptua. Dolores lorem magna kasd et eos aliquyam lorem, lorem justo sea clita nonumy vero et et. Sanctus erat sed ea accusam eos et lorem. Ipsum sit.dolore lorem stet kasd sit stet stet sed, et sea ea et vero voluptua sed aliquyam at tempor"
    }
]
